### ISSUE TITLE
[BUG]: incorrect icmp hash prevent icmp detection 

### ISSUE THREAD

**Issue by kotee4ko** [bi-zone/masscan-ng#4]
[Here](https://github.com/bi-zone/masscan-ng/blob/11ba60538af49ff23c17c36c720e2529e7724a40/src/proto-icmp.c#L73) Templ_ICMP_echo constans passed as src port to hash func. All icmp pkts use port 0. So, this is a bug.

**Comment by sc07kvm** [comment]
It doesn't matter, because the cookie[ICMP.Identifier + ICMP.SequenceNumber] is used as a pseudo-random identifier to only accept responses to your ICMP echo requests.
The cookies calculated in the same way are set [here](https://github.com/bi-zone/masscan-ng/blob/a8bc38dc45c20927534537c9af6ae45315b2795d/src/templ-pkt.c#L1003).

**Comment by kotee4ko** [comment]
But port_them is zero on icmp.
Anyway, in my env (vpn area) icmp scan doesn't work at all with Templ_ICMP_echo, and work ok with 0.

**Comment by sc07kvm** [comment]
Yes you are right. I will fix it.

**Comment by sc07kvm** [comment]
I fixed it. You can check.
